[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24
autorestart=true
priority=100

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":99"
autorestart=true
priority=200
depends_on=xvfb

[program:vnc]
command=/usr/bin/x11vnc -display :99 -forever -shared -rfbport 5900 -nopw
autorestart=true
priority=300
depends_on=xvfb

[program:novnc]
command=/opt/websockify/run --web /opt/novnc 6080 localhost:5900
autorestart=true
priority=400
depends_on=vnc

[program:gstreamer]
command=/usr/bin/gst-launch-1.0 ximagesrc display-name=:99 use-damage=0 show-pointer=true ! video/x-raw,framerate=30/1 ! x264enc speed-preset=ultrafast tune=zerolatency byte-stream=true key-int-max=30 ! rtph264pay config-interval=1 pt=96 ! gdppay ! tcpserversink host=0.0.0.0 port=8554
autorestart=true
priority=500
depends_on=xvfb

[program:roblox]
command=/startup.sh
autorestart=true
priority=600
depends_on=novnc
